name: Build binaries

on:
  release:
    types: [created]

jobs:
  binaries:
    name: Cross-platform binary builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.20"

      - name: Create directory
        run: mkdir dist

      - name: Build windows/amd64
        run: GOOS=windows GOARCH=amd64 go build -o dist/wsl2-ssh-pageant-amd64.exe

      - name: Build windows/arm64
        run: GOOS=windows GOARCH=arm64 go build -o dist/wsl2-ssh-pageant-arm64.exe

      - name: Upload build artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./dist/*
